### ISSUE TITLE
Bug with HeadPhones

### ISSUE THREAD

**Issue by darnat** [TheAmazingAudioEngine/TAAE2#11]
Hey Michael,

TAAE2 Lib seems to have a bug with the headphones. You can reproduce easily the bug with your sample.
Just kill the sample app,
Plug your headphones
launch the sample app and play a beat
The beat seems to be 2 times faster

**Comment by michaeltyson** [comment]
Hey @darnat - ouch. Hmm, I just tried that on my iPhone 6S Plus, and it sounds fine; unplugging and replugging sounds correct too. Can you tell me more about your setup?

**Comment by darnat** [comment]
Try to kill the app, unplug, then plug the headphones, and launch the sample app, the beat sounds working ?
I have an iPhone 6s

**Comment by michaeltyson** [comment]
Oh, yes! You're right - it seems I have to launch it from the home screen, not the debugger, or something. Right, I'm-a look into this. Cheers for the heads-up.

**Comment by darnat** [comment]
Ah Thank you very much, you are welcome !

**Comment by michaeltyson** [comment]
There we go. Forgot to start the audio session prior to querying some properties.
