### ISSUE TITLE
Question regarding `stopRecordingAtTime:completion` method of the `AEAudioFileRecorderModule` class

### ISSUE THREAD

**Issue by Augustyniak** [TheAmazingAudioEngine/TAAE2#13]
Hey,

Looking at the implementation of `stopRecordingAtTime:completion` method I noticed that it uses `NSTimer`. In fact, stopping of the recording is asynchronous and happens from within the implementation of `AEAudioFileRecorderModuleProcess` function. 

In my application I would like to be able to stop recording of the audio file even if input and output audio units are stopped. I stop audio units in order to implement `pause` functionality in my recorder.   Unfortunately, when these units are stopped, `AEAudioFileRecorderModuleProcess` function isn't called and consequently recording can't finish. 

Because of the reasons described above I have a few questions:
1. Is use of `NSTimer` in the implementation of `stopRecordingAtTime:completion` method necessary?
2. Are there any reasons against synchronous version of `stopRecordingAtTime:completion` method which would be able to finish recording even if all audio units are stopped?

And one more time - thanks for a great work!

**Comment by michaeltyson** [comment]
Just writing to let you know I'll get back to you soon - haven't quite found a convenient moment to respond just yet, but I will shortly =)

**Comment by michaeltyson** [comment]
Fair point, @Augustyniak. I've just committed a change which will allow stopRecordingAtTime:completion: to finish synchronously if 'time' is zero
