### ISSUE TITLE
AEAudioFilePlayerModule - Pause and Resume

### ISSUE THREAD

**Issue by renjithn** [TheAmazingAudioEngine/TAAE2#16]
Thanks for this making amazing project. Whats the best way to implement pause and resume in an AEAudioFilePlayerModule during playback?

The one idea I had was to persist the value of player.currentTime (AESeconds) on receiving a pause action and then later use this in the playAtTime method to resume. However the playAtTime seems to take a AudioTimeStamp not AESeconds.

**Comment by michaeltyson** [comment]
Hey @renjithn. You've got the right idea, but the timestamp passed to playAtTime refers to the time (in the world) that playback should start, not the playback position within the file. For that, you need to assign a value to currentTime.

**Comment by AlbertBoy** [comment]
So,whats the best way to implement pause and resume in an AEAudioFilePlayerModule during playback?
