### ISSUE TITLE
Overriding part of the audio file which is used as recording output

### ISSUE THREAD

**Issue by Augustyniak** [TheAmazingAudioEngine/TAAE2#18]
Hi,

I have a case as follows:
There is an option to record microphone input in my application. I implemented this functionality using `AEAudioFileRecorderModule` and everything works as expected. Now, I want to add user a possibility to remove _x last seconds_ from the recording and start recording again from the end of recording. 

I looked at the classes available in AAE2 and `AEAudioFileRecorderModule` API and I don't see how I can achieve that kind of functionality. Can you give me some tips that would allow me to implement desired behaviour?

**Comment by cgmaier** [comment]
You might want to check out AVMutableComposition for this.

**Comment by michaeltyson** [comment]
Yep, what @cgmaier said =)
