### ISSUE TITLE
Rename "Core Types" directory so bazel can build it

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#20]
It would be helpful if the "Core Types" directory was renamed to not have a space in it. (Maybe to "CoreTypes".)

The reason I'm asking for this change is that I'm trying to add TheAmazingAudioEngine to a project that's built using the bazel build system. Bazel (http://www.bazel.io/) has a limitation that it doesn't support directories (or files) with spaces in their names.

I can work around this issue by renaming my local copy of the "Core Types" directory, but it would be convenient if "Core Types" was renamed in the upstream TheAmazingAudioEngine2 project.

I'd be happy to submit a pull request that renames the directory, if you would like me to.

**Comment by hashmal** [comment]
Hopefully Bazel will be able to handle spaces in the future (it's still in beta after all.)
