### ISSUE TITLE
AEModule inputs other than audio?  

### ISSUE THREAD

**Issue by olympianoiseco** [TheAmazingAudioEngine/TAAE2#21]
Hi Michael,

I'm trying to get my head around how it might be structured within TAAE2 to have inputs other than the the render context be handled inside an AEModule subclass.  For example, if I were to create an LFO subclass of AEModule that doesn't generate audio per se, but rather a generates a "control signal" (in the form of an AudioBufferList) that I can access from inside other AEModule subclasses.  

Would I essentially create a separate context for the LFO, and then add a property to the subclass to access that context?  

Thanks for any guidance!
Ben

**Comment by michaeltyson** [comment]
Hey Ben. Hmm, probably better to use the LFO class directly, passing that around. I don't think AudioBufferLists are very appropriate for control signals.
