### ISSUE TITLE
Local TPCircularBuffer differs from https://github.com/michaeltyson/TPCircularBuffer

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#22]
The local version of TPCircularBuffer differs from https://github.com/michaeltyson/TPCircularBuffer.

(Looks like you added TPCircularBufferSetAtomic)

Having two versions of TPCircularBuffer makes it hard to use TAAE2 with large projects that also want to use TPCircularBuffer for other reasons.

Maybe the thing to do is update michaeltyson/TPCircularBuffer to match TAAE2 ?

**Comment by michaeltyson** [comment]
That's strange - it looks up to date to me (although I did just commit a documentation fix). TPCircularBufferSetAtomic is present: https://github.com/michaeltyson/TPCircularBuffer/blob/master/TPCircularBuffer.h#L114

**Comment by jackpal** [comment]
Oops. My mistake. My local copy of TPCircularBuffer is v1.1. I better go update it to v1.4.

Sorry for the false alarm.
