### ISSUE TITLE
AEDSPGenerateOscillator - maybe document that it's just a loose approximation of a sine wave

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#23]
Currently AEDSPGenerateOscillator's docs say
-  This function produces, sample by sample, a sine-line oscillator signal.

But the current formula is y = (x *\* 2 - 1) *\* 2 over the range -1..1, which is not a very accurate approximation of a real sine wave. People using this to debug their code might think that something was wrong with their audio processing pipeline.

I'd suggest either using an accurate approximation or documenting the the function produces a loose approximation of a sine wave.

**Comment by michaeltyson** [comment]
Bugger. That was meant to be "sine-like" rather than "sine-line" =)
