### ISSUE TITLE
Would you consider using NS_UNAVAILABLE and NS_DESIGNATED_INITIALIZER?

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#24]
Today I made a mistake by initializing an oscillator module in a test program as follows:

```
[[AEOscillatorModule alloc] init];
```

That compiled fine, but it didn't work (as I found out after debugging) because the oscillator module doesn't get initialized fully.

I should have written this instead:

```
[[AEOscillatorModule alloc] initWithRenderer:renderer];
```

Would you consider adding

```
- (instancetype)init NS_UNAVAILABLE;
```

and maybe also

   NS_DESIGNATED_INITIALIZER

in all the appropriate places in your public headers?

**Comment by michaeltyson** [comment]
Excellent idea

**Comment by hashmal** [comment]
In this particular case, `renderer` is marked as nullable, which means that `init` does not necessarily needs to be marked as unavailable. It could just call `initWithRenderer:nil` instead.

However, the last time I tried to pass `nil` to the initializer, my program crashed.
