### ISSUE TITLE
I wrote an AEAudioDataOutput class for use in my tests -- would it be useful in general?

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#26]
I made a new class, based on AEAudioFileOutput, but instead of writing to an audio file it just calls a "sink" block with each rendered buffer.

I wrote this to help me make automated tests that compare the rendered output to expected output.

Is this something you would be interested in putting in TAAE2? If you like, I can clean up my code and send a pull request.

It's fine if you're not interested, or if you'd rather do it your own way. I just wanted to check before going to the trouble of creating a pull request.

**Comment by jackpal** [comment]
Now that I've read through the forums, I see you're trying to keep TAAE2 as minimal as possible, to avoid accumulating technical debt. I don't think my class is important enough to add to TAAE2. I'll withdraw the issue.

**Comment by hashmal** [comment]
I think it could still be useful in a distinct repo, available as a… well, as a module. That way the core of TAAE2 stays lean, but people can mix/match additional components they find.
