### ISSUE TITLE
Readme Organization

### ISSUE THREAD

**Issue by lfarah** [TheAmazingAudioEngine/TAAE2#28]
Hey, your library is really interesting.

The only problem I found was the `README.md`, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.

If you want, I can help you to do it.

What are your thoughts?

**Comment by lfarah** [comment]
@michaeltyson Why? 😢

**Comment by michaeltyson** [comment]
Oh, beg your pardon - this looked spammy so I just closed it, didn't realise you weren't a bot 😄

Nah, this is low priority.

**Comment by lfarah** [comment]
I'm the organizer of [AwesomeiOS](https://github.com/vsouza/awesome-ios), so I look through dozens of libraries per day and I always help them to improve. Because they have really similar problems, I have a set of pre-made texts so I can quickly open issues
