### ISSUE TITLE
Should AEAudioFileOutput call AEManagedValueCommitPendingUpdates ?

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#34]
The docs for AEManagedValueCommitPendingUpdates state:

"If you are not using AEAudioUnitOutput, then you must call the AEManagedValueCommitPendingUpdates function at the beginning of your main render loop."

But in reading AEAudioFileOutput, I don't see where AEManagedValueCommitPendingUpdates is called. Should it be called somewhere near line 71 of AEAudioFileOutput.m? (Top of the while loop inside of |AEAudioFileOutput runForDuration:completionBlock:|

**Comment by michaeltyson** [comment]
Hmm.. is your repo definitely up to date? https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine2/blob/master/TheAmazingAudioEngine/Outputs/AEAudioUnitOutput.m#L84

Update: Oops, beg your pardon, I misread; you're talking about AEAudioFileOutput. That's deliberately not in there because it'll mess things up if you're using both AEAudioFileOutput and AEAudioUnitOutput at the same time. There may be a way around that, but I've not gotten to it yet =)

**Comment by michaeltyson** [comment]
...I don't think it makes a lot of sense to be altering variable values while doing an offline render anyway, at least not without stopping first (by running for a short time, then updating values, then running some more). So having it within the offline render loop itself probably wouldn't fly.

**Comment by jackpal** [comment]
FWIW I'm using my offline renderer as part of a my apps automated tests. I can run my app with either the online renderer or the offline renderer. In that scenario it is important that my offline renderer call AEManagedValueCommitPendingUpdates at the start of its render loop, otherwise it won't work like the online renderer.

My offline renderer is loosely based on AEAudioFileOutput. So I figure if my offline renderer needs  AEManagedValueCommitPendingUpdates, then so would AEAudioFileOutput.

Indeed, it only makes sense in a world where one output module is active at a time.
(Unless AEManagedValues were associated with a specific output module.)

**Comment by michaeltyson** [comment]
Ah, got it - I can imagine that if you're running the offline system in lock-step with some main thread activity, that would definitely make sense to call Commit there. I'd say the best approach is to put it in the top of your test output loop, in that case. I think it's probably best left out of the audio file output still, though, as I can see scope for some unpredictable behaviour if it's in there automatically.
