### ISSUE TITLE
Port AEExpanderFilter from TAAE -> TAAE2

### ISSUE THREAD

**Issue by manderson-productions** [TheAmazingAudioEngine/TAAE2#35]
Hi there!

Was wondering if the implementation for the `AEExpanderFilter` from TAAE is in scope for the beta or release version of TAAE2? This was a very useful filter and would IMO be a good addition to the filter modules in TAAE2.

If one were to implement this filter, what are your thoughts on how it should be implemented? The TAAE version is available here: https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/blob/master/Modules/AEExpanderFilter.m

Thanks!

**Comment by michaeltyson** [comment]
Actually, [AEDynamicsProcessorModule](http://theamazingaudioengine.com/doc2/interface_a_e_dynamics_processor_module.html) should fulfil the same role.

**Comment by manderson420** [comment]
Yup, you're totally right. I ended up using that audio unit to get the desired result. Thanks!

**Comment by manderson-productions** [comment]
Yup, you're totally right. I ended up using that audio unit to get the desired result. Thanks!
