### ISSUE TITLE
Problem Record Input

### ISSUE THREAD

**Issue by darnat** [TheAmazingAudioEngine/TAAE2#8]
I think the library has a main issue which that is impossible to record only the input, it causes a EXC_BAD_ACCESS on "ExtAudioFileWriteAsync"

**Comment by michaeltyson** [comment]
Hey - please attach a small sample app that demonstrates the issue

**Comment by darnat** [comment]
Hey ! Well, the problem appear on your TAAE2 sample if:
- I comment the line **189** & **190** `AEModuleProcess(micDelay, context);
  AEModuleProcess(micBandpass, context);` of AEAudioController.m
- Comment also the line **208** `AEBufferStackMix(context->stack, 2);`

Then I just launch in this order the loop "BEAT", enable the input, then record - The app will often crash.

**Comment by michaeltyson** [comment]
Ah! Excellent, thank you very much! Reproduced, diagnosed and fixed in SHA b3dabe4072121fee089365b38e79ae49bfb862dd
