### ISSUE TITLE
Confused on how to add the library to a project

### ISSUE THREAD

**Issue by mitchellporter** [TheAmazingAudioEngine/TAAE2#9]
Hey Michael,

First off thanks for all of the hard work that you put into the original TAAE, this is my first time using it but have been a fan and following the progress over the years. Was really interested in this re-write, so wanted to start testing it.

I had no problem installing the original TAAE via Cocoapods in a project a few minutes ago, but having trouble installing this one. I dragged the files over from the sample, but i'm getting "file not found" errors in TheAmazingAudioEngine.h file.

Am I understanding correctly that this is a new library, or is it still utilizing the old one? Would love to install this ASAP so I can continue testing.

Thanks.

**Comment by michaeltyson** [comment]
Hi @mitchellporter,

You'll want to clone the repository within a folder in your project (I usually use a folder called "Library"), then drag the TheAmazingAudioEngine.xcodeproj file into your project. Find your app's build target, then go into Build Phases and add the TheAmazingAudioEngine target to the Target Dependencies list, and then add libTheAmazingAudioEngine.a to the Link Binary With Libraries list. Finally, locate the Header Search Paths setting within Build Settings, and add `"$(SRCROOT)/Library/TheAmazingAudioEngine"` (it may have done that automatically). That should do it.

I'll be adding a Cocoapods repository as soon as TAAE2's out of beta (which will be soonish - once I'm done writing the documentation)

**Comment by mitchellporter** [comment]
@michaeltyson Thanks for the fast reply. I followed your directions exactly, and I'm still running into the same issue. I created a new folder in my project's folder called `TAAE2` and cloned the repo into it. Followed all of your steps. I'm still getting the file not found error in the `TheAmazingAudioEngine.h` file.

I'm fairly certain what I entered for the Header Search Paths is correct: `"$(SRCROOT)/TAAE2/TheAmazingAudioEngine"`

Am I correct that the error most likely has to do with the Header Search Path not being correct? I'm going to create a quick test project, follow your instructions, reproduce the error, and will link you to it.

**Comment by michaeltyson** [comment]
No problem =) Yeah, it's going to be a search path problem. I think you need to have just `"$(SRCROOT)/TAAE2"`, though - don't add the extra path component.

**Comment by mitchellporter** [comment]
Ok so I tried your most recent comment, along with a ton of random experimentation but still couldn't get it to work. Apparently header search paths are my ultimate weakness.

Here's the test project I just made. I followed your instructions exactly. I included some extras in the project like my typical Podfile setup etc. in case that was affecting anything.: https://github.com/mitchellporter/TAAE2Error

Thanks for the help.

**Comment by michaeltyson** [comment]
Ah, you're working with a workspace (duh)! That makes it a lot easier. Just set your header search paths to `"$(BUILT_PRODUCTS_DIR)"`, and for release, add `"$(TEMP_ROOT)/UninstalledProducts/$(PLATFORM_NAME)"` as well.

(Take a look at TAAESample's build settings)

**Comment by mitchellporter** [comment]
Ha, it builds now! This is what happens when you rely on Cocoapods for dependency management instead of getting your hands dirty. Thanks for the help I really appreciate it. Excited to get back to testing!

**Comment by michaeltyson** [comment]
No worries =)

Yeah, I tend to avoid using Cocoapods as I prefer to have more control over dependencies, but that's just me!

**Comment by mitchellporter** [comment]
I just sent you an email :)

Thanks again for the help and all your hard work on TAAE cheers.
